line = input().split()
a = float(line[0])
b = float(line[1])
c = float(line[2])
print(f"TRIANGULO: {a * c / 2:.3f}")
print(f"CIRCULO: {3.14159 * c**2:.3f}")
print(f"TRAPEZIO: {((a + b) * c) / 2:.3f}")
print(f"QUADRADO: {b**2:.3f}")
print(f"RETANGULO: {a * b:.3f}")
